name: laravel_forge
description: A Laravel forge app.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5
  dio: ^5.2.1+1
  flutter_secure_storage: ^8.0.0
  google_fonts: ^5.1.0
  unicons: ^2.1.1
  flutter_highlighter: ^0.1.1
  tint: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.2
  change_app_package_name: ^1.1.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: false
  image_path: "assets/icon/icon.png"

flutter:
  uses-material-design: true
