name: Create Release

on:
  push:
    branches:
    - main
jobs:
  android-build:
    runs-on: ubutunu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '12'
          cache: 'gradle'
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.10.5'
          channel: 'stable'
          cache: true
      - run: flutter pub get
      - run: flutter build apk
      - run: flutter build appbundle
  windows-build:
    runs-on: windows-latest
    steps:
       - uses: actions/checkout@v3
       - uses: subosito/flutter-action@v2
         with:
           channel: 'stable'
           cache: true
       - run: flutter config --enable-windows-desktop
       - run: flutter build windows
