name: Create Release

on:
  push:
    branches:
    - main
jobs:
  android-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '12'
          cache: 'gradle'
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.10.5'
          channel: 'stable'
          cache: true
      - run: flutter pub get
      - run: flutter build apk
      - run: flutter build appbundle
      - uses: actions/upload-artifact@v3
        with:
          name: release-apk
          path: build/app/outputs/apk/release/app-release.apk
  windows-build:
    runs-on: windows-latest
    steps:
       - uses: actions/checkout@v3
       - uses: subosito/flutter-action@v2
         with:
           channel: 'stable'
           cache: true
       - run: flutter config --enable-windows-desktop
       - run: flutter build windows
       - uses: actions/upload-artifact@v3
         with:
          name: release-windows
          path: build\windows\runner\Release\laravel_forge.exe
  linux-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true
      - run: |
         sudo apt-get update -y
         sudo apt-get install -y ninja-build libgtk-3-dev libsecret-1-dev libjsoncpp-dev
      - run: flutter config --enable-linux-desktop
      - run: flutter build linux --release
      - uses: actions/upload-artifact@v3
        with:
          name: release-linux
          path: build/linux/x64/release/bundle/
    
